### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by huayunh** [pxblue/angular-showcase-demo#9]
A list of style issues I noticed so far in the demo project: 

# /dashboard
## 1
![image](https://user-images.githubusercontent.com/8997218/97462983-a8af4b00-1915-11eb-83dc-b14abb87aad6.png)
- The expansion panel should be 48px tall. 
- The chevron should be centered.

## 2
![image](https://user-images.githubusercontent.com/8997218/97463280-f330c780-1915-11eb-87bf-1da982c861cc.png)
- These icons should be vertically aligned

## 3
![image](https://user-images.githubusercontent.com/8997218/97463485-2c693780-1916-11eb-8cf9-e4543f3c1c3a.png)
- make `.tag-label` 16px margin on the right instead of 8px

## 4
![image](https://user-images.githubusercontent.com/8997218/97463618-53276e00-1916-11eb-91c2-e9a09f62b4f2.png)
- If possible, make the "alarm" list item use 600 font-weight and red[500] text when there are some alarm present; otherwise, have them stay font-weight 400 and regular text color black 500. 

## 5
![image](https://user-images.githubusercontent.com/8997218/97463865-984ba000-1916-11eb-86f4-056ccc52db31.png)
- Drawer active item should be using blue 500? 

## 6 
![image](https://user-images.githubusercontent.com/8997218/97466045-0c874300-1919-11eb-87a3-4b27814d723f.png)
There should not be a divider for the last item on the list. 

# /timeline 
## 1
![image](https://user-images.githubusercontent.com/8997218/97464026-c8933e80-1916-11eb-9451-5eede01d0684.png)
- Icon with avatar should be white[50] in the center. 

## 2 
![image](https://user-images.githubusercontent.com/8997218/97464331-2a53a880-1917-11eb-83e3-ac8789a21bf8.png)

Card header should use subtitle 2 font, with a 16px distance to the left

## 3
![image](https://user-images.githubusercontent.com/8997218/97464427-448d8680-1917-11eb-8041-23c62ecf08c3.png)

Card has a round corner, but the stripe appears to spill over. 

## 4 
Again, all icons should be center-aligned.

## 5 
![image](https://user-images.githubusercontent.com/8997218/97464762-b239b280-1917-11eb-9dc2-b8d90d3c0ee7.png)

List item tags should be vertically centered 

## 6
![image](https://user-images.githubusercontent.com/8997218/97465076-0e043b80-1918-11eb-8246-318d71eea475.png)
The timestamp can use a bit less room. (The design on the bottom comes from Figma)

## 7 
Again, card header should be 48px, not 50px

## 8
![image](https://user-images.githubusercontent.com/8997218/97465254-3db34380-1918-11eb-9138-a684ca9a48e5.png)

~This guy should be 48px tall too.~

Update: check with Kyle Horchen.

## 9
![image](https://user-images.githubusercontent.com/8997218/97465356-56bbf480-1918-11eb-96e9-5040e6fbf2fe.png)

Don't use `<br />` to space the cards. I recommend a 16px margin-top, and a 24px padding between app bar and the first card element

## 10
Keep the time format consistent. Don't sometimes show the dates and sometimes don't.
![image](https://user-images.githubusercontent.com/8997218/97465727-b7e3c800-1918-11eb-8466-50b74f6d2914.png)

**Comment by joebochill** [comment]
Make sure to double check with the team on this before implementing all of the changes. Some of these _might_ be okay as is.
